# This is a basic workflow to help you get started with Actions

name: WakaTime status update

# Controls when the workflow will run
on:
  push:
    branches: [main]
  schedule:
    # Runs at 12 am  '0 0 * * *'  UTC
    - cron: "1 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-readme:
    name: Update the WakaTime Stat
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: MrInternauta/MrInternauta@main
        with:
          # WakaTime API key stored in secrets, do not directly paste it here
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Automatic github token
          GITHUB_TOKEN: ${{ github.token }}
          USERNAME: MrInternauta
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          # Branch - newer GitHub repositories have "main" as default branch, change to main in that case, default is master
          BRANCH: "main"
          # Manual Commit messages - write your own messages here
          COMMIT_MSG: "Automated Coding Activity Update :alien:"
